<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-02-18 13:52
=======
# Generated by Django 4.0.1 on 2022-02-13 14:54
>>>>>>> ab7cf97dc1a97c22b868e42232d3514fb62f617b

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('flower_name', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
                ('etymology', models.TextField()),
                ('evolution', models.TextField()),
                ('species', models.TextField()),
                ('tax_domain', models.CharField(max_length=100)),
                ('tax_kingdom', models.CharField(max_length=100)),
                ('tax_phylum', models.CharField(max_length=100)),
                ('tax_order', models.CharField(max_length=100)),
                ('tax_family', models.CharField(max_length=100)),
                ('tax_genus', models.CharField(max_length=100)),
                ('ornamental_plants', models.TextField()),
                ('cut_flowers', models.TextField()),
                ('medicinal_uses', models.TextField()),
                ('health_benefits', models.TextField()),
                ('perfumes_food', models.TextField()),
                ('symbolizes', models.TextField()),
                ('season_to_grow', models.TextField()),
=======
                ('Flower_name', models.CharField(max_length=50)),
                ('Introduction', models.TextField()),
                ('Etymology', models.TextField()),
                ('Evolution', models.TextField()),
                ('Species', models.TextField()),
                ('Tax_domain', models.CharField(max_length=50)),
                ('Tax_kingdom', models.CharField(max_length=50)),
                ('Tax_phylum', models.CharField(max_length=50)),
                ('Tax_order', models.CharField(max_length=50)),
                ('Tax_family', models.CharField(max_length=50)),
                ('Tax_genus', models.CharField(max_length=50)),
                ('Ornamental_plants', models.TextField()),
                ('Cut_flowers', models.TextField()),
                ('Medicinal_uses', models.TextField()),
                ('Health_benefit', models.TextField()),
                ('Perfumes_food', models.TextField()),
                ('Symbolizes', models.TextField()),
                ('Season_to_grow', models.TextField()),
>>>>>>> ab7cf97dc1a97c22b868e42232d3514fb62f617b
            ],
        ),
    ]
