# Generated by Django 4.0.1 on 2022-02-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
                ('etymology', models.TextField()),
                ('evolution', models.TextField()),
                ('species', models.TextField()),
                ('tax_domain', models.CharField(max_length=100)),
                ('tax_kingdom', models.CharField(max_length=100)),
                ('tax_phylum', models.CharField(max_length=100)),
                ('tax_order', models.CharField(max_length=100)),
                ('tax_family', models.CharField(max_length=100)),
                ('tax_genus', models.CharField(max_length=100)),
                ('ornamental_plants', models.TextField()),
                ('cut_flowers', models.TextField()),
                ('medicinal_uses', models.TextField()),
                ('health_benefits', models.TextField()),
                ('perfumes_food', models.TextField()),
                ('symbolizes', models.TextField()),
                ('season_to_grow', models.TextField()),
            ],
        ),
    ]
